default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: beetle_maps_development

test:
  <<: *default
  database: beetle_maps_test

production:
  <<: *default
  database: beetle_maps_production
  username: beetle_maps
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

